CREATE TABLE IF NOT EXISTS users(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 role TEXT CHECK(role IN ('physio','patient')) NOT NULL,
 name TEXT
);
CREATE TABLE IF NOT EXISTS exercises(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT);
CREATE TABLE IF NOT EXISTS schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,
 patient_id INTEGER,exercise_id INTEGER,scheduled_at DATETIME,completed INTEGER DEFAULT 0);
